// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package web

import (
	. "maragu.dev/gomponents"

	// Section is an <h2> with an anchor, and whatever follows it.

	html "maragu.dev/gomponents/html"

	"strings"
)

func Section(id string, title string, children ...Node) Node {
	return Group{html.H2(html.ID(id), Text(title)), Group(children)}
}

// Snippet is a labelled code block. The label says what language it is and,
// more usefully, which file it belongs in.
func Snippet(lang string, label string, code string) Node {
	body := html.Pre(html.Code(Raw(highlight(lang, strings.TrimSpace(code)))))

	if label == "" {
		return body
	}

	return html.Div(
		html.Class("snippet"),
		html.Div(html.Class("snippet-label"), Text(label)),
		body,
	)
}

// Code is a labelled code block with the language as its label.
func Code(lang string, code string) Node {
	return Snippet(lang, lang, code)
}

// Note is an aside the reader should not skip.
func Note(title string, children ...Node) Node {
	return html.Div(
		html.Class("note"),
		If(title != "", html.Strong(html.Class("note-title"), Text(title))),
		Group(children),
	)
}

// Cols puts two blocks side by side, for a before and an after.
func Cols(left Node, right Node) Node {
	return html.Div(html.Class("cols"), left, right)
}

// Steps is a numbered list.
func Steps(items ...Node) Node {
	var lis []Node
	for _, item := range items {
		// The `var … Node` is load-bearing. GSX compiles an interpolated
		// expression to Text() unless it can read the declared type off a local,
		// and it does not follow a range variable back to its slice — so
		// {item} would try to print a Node as a string, and not compile.
		var body Node = item
		lis = append(lis, html.Li(body))
	}
	return html.Ol(html.Class("steps"), Group(lis))
}

// Pull is a sentence worth stopping on.
func Pull(children ...Node) Node {
	return html.P(html.Class("pull"), Group(children))
}

// Table renders a header row and body rows.
func Table(headers []string, rows [][]Node) Node {
	var ths []Node
	for _, h := range headers {
		ths = append(ths, html.Th(Text(h)))
	}

	var trs []Node
	for _, row := range rows {
		var tds []Node
		for _, cell := range row {
			var body Node = cell
			tds = append(tds, html.Td(body))
		}
		trs = append(trs, html.Tr(Group(tds)))
	}

	return html.Table(html.THead(html.Tr(Group(ths))), html.TBody(Group(trs)))
}

// Bolt is the mark without its rounded square, for use inside a control that
// already has a shape of its own.
func Bolt() Node {
	return html.SVG(
		html.Class("bolt"),
		Attr("viewBox", "0 0 32 32"),
		html.Width("15"),
		html.Height("15"),
		Attr("aria-hidden", "true"),
		El(
			"path",
			Attr("d", "M18 5 L9 18 h5 l-2 9 l9 -13 h-5 z"),
			Attr("fill", "currentColor"),
		),
	)
}

// C is inline code.
func C(s string) Node { return html.Code(Text(s)) }

// Row is a shorthand for a table row.
func Row(cells ...Node) []Node { return cells }
