// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package web

import (
	. "maragu.dev/gomponents"

	// Layout renders the complete document.
	//
	// It always renders the complete document. fx asks for one and takes what it
	// needs; a server that tried to guess which fragments to send would have to be
	// right every time, and this one only has to be right once.

	html "maragu.dev/gomponents/html"

	"os"
)

func Layout(c *Ctx) Node {
	title := c.Page.Title
	if c.Page.Slug != "" {
		title += " — fx"
	}

	mainClass := "content"
	if c.Page.Wide {
		mainClass += " wide"
	}

	var body Node = c.Page.Body(c)

	return Group{
		Raw("<!doctype html>\n"),
		html.HTML(
			html.Lang("en"),
			html.Head(
				html.Meta(html.Charset("utf-8")),
				html.Meta(
					html.Name("viewport"),
					html.Content("width=device-width, initial-scale=1"),
				),
				html.TitleEl(html.ID("page-title"), Attr("fx-hungry"), Text(title)),
				html.Meta(html.Name("description"), html.Content(c.Page.description())),
				html.Link(html.Rel("icon"), html.Href(favicon)),
				El("style", Raw(stylesheet)),
				html.Script(html.Src("/fx.js")),
				If(!isProduction(), html.Script(html.Src("/fx.dev.js"))),
			),
			html.Body(
				html.Div(html.ID("progress-bar")),
				html.A(html.Class("skip-link"), html.Href("#content"), Text("Skip to content")),
				html.Header(
					html.Class("top"),
					html.Div(
						html.Class("top-inner"),
						html.A(
							html.Class("brand"),
							html.Href("/"),
							Attr("fx-target", "#content"),
							Attr("fx-loading-target", "#progress-bar"),
							Mark(),
							Text("fragment exchange"),
						),
						Nav(c),
					),
				),
				html.Div(
					html.Class("shell"),
					html.Main(
						html.ID("content"),
						html.Class(mainClass),
						PageHead(c),
						body,
						Footer(),
					),
				),
			),
		),
	}
}

// Nav is hungry, so the current page updates even though links only ever ask
// for #content.
func Nav(c *Ctx) Node {
	var links []Node
	for _, p := range Pages() {
		if p.Nav == "" {
			continue
		}

		current := p.Slug == c.Page.Slug
		links = append(links, html.A(
			html.Href(p.Path()),
			Attr("fx-target", "#content"),
			Attr("fx-loading-target", "#progress-bar"),
			If(current, Attr("aria-current", "page")),
			Text(p.Nav),
		))
	}

	return html.Nav(
		html.ID("primary-nav"),
		html.Class("primary"),
		Attr("fx-hungry"),
		Group(links),
		html.A(
			html.Href("https://github.com/kilianc/fragment-exchange"),
			Text("GitHub"),
		),
	)
}

func PageHead(c *Ctx) Node {
	if c.Page.Title == "" {
		return nil
	}

	heading := c.Page.Headline
	if heading == "" {
		heading = c.Page.Title
	}

	return html.Div(
		html.Class("page-head"),
		html.H1(Text(heading)),
		If(c.Page.Tagline != "", html.P(html.Class("tagline"), Text(c.Page.Tagline))),
		If(c.Page.Lede != "", html.P(html.Class("lede"), Text(c.Page.Lede))),
	)
}

func Footer() Node {
	return html.Footer(
		html.Class("bottom"),
		html.Span(Text("fx v"), Text(fxVersion), Text(" · MIT")),
		html.A(
			html.Href("https://github.com/kilianc/fragment-exchange"),
			Text("Source"),
		),
		html.Span(
			html.Class("muted"),
			Text(
				"This page was rendered by a Go server and swapped in by the library it documents.",
			),
		),
	)
}

// Mark is the bolt from the favicon and the README logo, inline so the header,
// the tab icon and the wordmark in assets/ are all the same drawing.
func Mark() Node {
	return html.SVG(
		html.Class("mark"),
		Attr("viewBox", "0 0 32 32"),
		html.Width("22"),
		html.Height("22"),
		Attr("aria-hidden", "true"),
		El(
			"rect",
			html.Width("32"),
			html.Height("32"),
			Attr("rx", "8"),
			Attr("fill", "currentColor"),
		),
		El(
			"path",
			Attr("d", "M18 5 L9 18 h5 l-2 9 l9 -13 h-5 z"),
			Attr("fill", "var(--accent-fg)"),
		),
	)
}

// A lightning bolt in a rounded square, as a data URI. One less request, and
// no binary in the repository.
const favicon = "data:image/svg+xml," +
	"%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E" +
	"%3Crect width='32' height='32' rx='8' fill='%232563eb'/%3E" +
	"%3Cpath d='M18 5 L9 18 h5 l-2 9 9-13 h-5 z' fill='white'/%3E%3C/svg%3E"

func isProduction() bool {
	return os.Getenv("VERCEL_ENV") == "production" || os.Getenv("PRODUCTION") == "true"
}
