// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package web

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func ReferencePage() Page {
	return Page{
		Slug:  "reference",
		Nav:   "Reference",
		Title: "Reference",
		Lede:  "Everything fx does. It is a short page on purpose — if it were long, the library would have failed.",
		Body:  referenceBody,
	}
}

func referenceBody(c *Ctx) Node {
	return Group{
		Section(
			"attributes",
			"Attributes",
			Table(
				[]string{"Attribute", "On", "Effect"},
				[][]Node{
					Row(
						C("fx-target"),
						C("<a>, <form>"),
						Text(
							"Fetch the destination, then replace these selectors with the matching elements from the response. A comma-separated list.",
						),
					),
					Row(
						C("fx-loading-target"),
						C("<a>, <form>, <meta>"),
						Text(
							"Add the fx-loading class to everything matching these selectors while the request is in flight, and remove it afterwards.",
						),
					),
					Row(
						C("fx-hungry"),
						Text("any element with an id"),
						Text(
							"Swap this element on every navigation, whether or not the link asked for it. Requires an id; without one it is ignored.",
						),
					),
					Row(
						C("fx-interval"),
						C(`<meta name="fx-refresh">`),
						Text("Re-fetch the current URL every N milliseconds and swap fx-target."),
					),
				},
			),
			html.P(
				Text(
					"A selector is any CSS selector, but in practice it should be an id. Two elements matching the same selector make the swap ambiguous, and fx picks the first one.",
				),
			),
		),
		Section(
			"links",
			"Links",
			Code(
				"html",
				`
<a href="/reports?status=open" fx-target="#content">Open reports</a>
<a href="/reports" fx-target="#content, #summary" fx-loading-target="#progress-bar">All</a>
`,
			),
			html.P(
				Text("The "),
				html.Code(Text("href")),
				Text(
					" is a real URL to a real page. fx pushes it, fetches it, and swaps. The address bar always shows a URL your server can render on its own.",
				),
			),
			html.P(
				Text("fx leaves a click alone — the browser handles it normally — when:"),
			),
			html.Ul(
				html.Li(Text("it is not a left click, or Cmd, Ctrl, Shift or Alt is held")),
				html.Li(
					Text("the link has "),
					html.Code(Text("target")),
					Text(" set to anything but "),
					html.Code(Text("_self")),
				),
				html.Li(
					Text("the link has a "),
					html.Code(Text("download")),
					Text(" attribute"),
				),
			),
		),
		Section(
			"forms",
			"Forms",
			Code(
				"html",
				`
<form action="/reports" method="GET" fx-target="#results" fx-loading-target="#results">
  <input type="search" name="q">
  <button type="submit">Search</button>
</form>
`,
			),
			html.P(Text("Form submission follows what the browser would have done:")),
			html.Ul(
				html.Li(
					html.Strong(Text("GET")),
					Text(
						" puts the fields in the query string, so the URL describes the result — which is the point.",
					),
				),
				html.Li(
					html.Strong(Text("POST")),
					Text(" sends "),
					html.Code(Text("application/x-www-form-urlencoded")),
					Text(", or"),
					Text(" "),
					html.Code(Text("multipart/form-data")),
					Text(" if the form has "),
					html.Code(Text("enctype=\"multipart/form-data\"")),
					Text(" "),
					Text("or a file selected."),
				),
				html.Li(
					Text("The submit button's "),
					html.Code(Text("name")),
					Text(" and "),
					html.Code(Text("value")),
					Text(" are included, and only the button that was actually pressed."),
				),
				html.Li(
					html.Code(Text("formaction")),
					Text(" and "),
					html.Code(Text("formmethod")),
					Text(" on the button override the form's."),
				),
				html.Li(
					Text("The button is disabled and given "),
					html.Code(Text("fx-loading")),
					Text(" for the duration of the request."),
				),
				html.Li(
					Text(
						"If the response is a redirect, fx swaps the fragments from where it landed and puts that URL in the address bar. Post, redirect, get, without thinking about it.",
					),
				),
			),
		),
		Section(
			"hungry",
			"fx-hungry",
			Code(
				"html",
				`
<title id="page-title" fx-hungry>Reports — Acme</title>
<nav id="primary-nav" fx-hungry>…</nav>
`,
			),
			html.P(
				Text(
					"Some parts of a page change on every navigation and no link should have to know about them: the document title, the active state in the nav, an unread count. Mark them hungry and the server decides — if the response contains the element, it is swapped.",
				),
			),
			html.P(
				Text(
					"Hungry elements are collected from both the current page and the response, so a fragment can introduce a new hungry element and it will still be picked up.",
				),
			),
		),
		Section(
			"refresh",
			"Polling",
			Code(
				"html",
				`
<meta name="fx-refresh" id="jobs-poll" fx-interval="5000" fx-target="#jobs">
`,
			),
			html.P(
				Text("This is "),
				html.Code(Text("<meta http-equiv=\"refresh\">")),
				Text(
					" for one fragment. Every five seconds fx re-fetches the current URL and swaps ",
				),
				html.Code(Text("#jobs")),
				Text("."),
			),
			html.P(Text("Timers stop on their own, which is the part that matters:")),
			html.Ul(
				html.Li(
					Text(
						"when the URL changes, every timer and every in-flight request is cancelled",
					),
				),
				html.Li(
					Text("when a swap removes the "),
					html.Code(Text("<meta>")),
					Text(" from the document, its timer is cancelled with it"),
				),
			),
			Note(
				"Put it in the body, not the head",
				html.P(
					Text(
						"The tag has to sit inside a fragment that gets swapped — usually inside the element your links target. Left in ",
					),
					html.Code(Text("<head>")),
					Text(
						" it survives every navigation, and you will be polling a page you already left.",
					),
				),
			),
			html.P(
				Text(
					"The interval is the gap between the end of one request and the start of the next, so a slow server does not queue up work behind itself.",
				),
			),
		),
		Section(
			"loading",
			"Loading state",
			html.P(
				html.Code(Text("fx-loading-target")),
				Text(" puts the "),
				html.Code(Text("fx-loading")),
				Text(
					" class on elements for the duration of a request. What that looks like is entirely your CSS. This site uses a bar:",
				),
			),
			Code(
				"html",
				`
<div id="progress-bar"></div>
<a href="/reports" fx-target="#content" fx-loading-target="#progress-bar">Reports</a>
`,
			),
			Code(
				"css",
				`
#progress-bar { height: 2px; width: 0; background: rebeccapurple; opacity: 0; }
#progress-bar.fx-loading { width: 70%; opacity: 1; transition: width 900ms; }
`,
			),
		),
		Section(
			"config",
			"Runtime configuration",
			html.P(
				Text("Set these on the "),
				html.Code(Text("fx")),
				Text(" global whenever you like. There is no init call and no config object."),
			),
			Table(
				[]string{"Property", "Default", "What it does"},
				[][]Node{
					Row(
						C("fx.timeout"),
						C("10000"),
						Text("Milliseconds before a request is aborted and the fallback runs."),
					),
					Row(
						C("fx.clickFallback"),
						C("location.replace(url)"),
						Text("Called when a link navigation fails."),
					),
					Row(
						C("fx.submitFallback"),
						C("form.submit()"),
						Text("Called with the form when a submission fails."),
					),
					Row(
						C("fx.historyFallback"),
						C("location.reload()"),
						Text("Called when a back or forward navigation fails."),
					),
					Row(C("fx.version"), C(`"`+fxVersion+`"`), Text("The version you have.")),
					Row(
						C("fx.logInfo / logDebug / logWarn / logError"),
						C("noop"),
						Text("Logging hooks. fx.dev.js fills them in; in production they do nothing."),
					),
				},
			),
			Code(
				"js",
				`
fx.timeout = 30_000;
fx.clickFallback = (url, err) => {
  reportToSentry(err);
  window.location.replace(url);
};
`,
			),
		),
		Section(
			"protocol",
			"The server protocol",
			html.P(
				Text("Every fx request carries an "),
				html.Code(Text("FX-Target")),
				Text(" header listing the selectors the browser is about to swap:"),
			),
			Code(
				"http",
				`
GET /reports?status=open HTTP/1.1
FX-Target: #content, #primary-nav, #page-title
`,
			),
			html.P(
				Text("The header lists everything this navigation will swap: the link's "),
				html.Code(Text("fx-target")),
				Text(", plus every "),
				html.Code(Text("fx-hungry")),
				Text(
					" element currently on the page. A hungry fragment your handler skipped would not be in the response, and would silently stop updating — so fx names them up front rather than letting you find out later.",
				),
			),
			html.P(
				Text(
					"You may ignore it completely. Return the whole document and everything works — that is the default, and it is why an existing handler needs no changes at all.",
				),
			),
			html.P(
				Text(
					"When a page has something expensive on it, read the header and skip what nobody asked for:",
				),
			),
			Snippet(
				"go",
				"handler",
				`
func reports(w http.ResponseWriter, r *http.Request) {
	page := Page{Filters: parseFilters(r)}

	// True on an ordinary page load, and on a fragment request that named it.
	if fx.Wants(r, "#results") {
		page.Results = search(r)        // 400ms
	}
	if fx.Wants(r, "#summary") {
		page.Summary = aggregate(r)     // 900ms
	}

	render(w, page)
}
`,
			),
			Note(
				"The default has to be “render it”",
				html.P(
					html.Code(Text("fx.Wants")),
					Text(
						" returns true whenever the header is absent, so a page load, a crawler, a curl and a browser with JavaScript disabled all get the whole page. Skipping work is an optimisation you opt into for a request that told you it was safe.",
					),
				),
			),
			html.P(
				Text(
					"If you cache responses, vary on the header — two requests for the same URL can now legitimately have different bodies:",
				),
			),
			Code("http", `Vary: FX-Target`),
		),
		Section(
			"go",
			"The Go package",
			html.P(
				Text(
					"Optional. fx is a JavaScript file and works with any server. If yours is Go, this saves you writing the same twenty lines:",
				),
			),
			Code("bash", `go get github.com/kilianc/fragment-exchange`),
			Snippet(
				"go",
				"main.go",
				`
import fx "github.com/kilianc/fragment-exchange"

mux.Handle("GET /fx.js", fx.Handler())     // served from the binary

fx.IsFragment(r)                            // did fx make this request?
fx.Targets(r)                               // []string{"#content", "#page-title"}
fx.Wants(r, "#results")                     // render this fragment?
fx.WantsAny(r, "#results", "#summary")      // render either?
fx.Script()                                 // the file itself, if you'd rather serve it yourself
`,
			),
		),
		Section(
			"dev",
			"fx.dev.js",
			html.P(
				Text("A development companion. Load it after "),
				html.Code(Text("fx.js")),
				Text(" and never in production:"),
			),
			Code(
				"html",
				`
<script src="/fx.js"></script>
<script src="/fx.dev.js"></script>  <!-- development only -->
`,
			),
			html.P(
				Text(
					"It turns on logging and checks every document fx parses for the silent mistakes:",
				),
			),
			html.Ul(
				html.Li(
					Text("an "),
					html.Code(Text("fx-hungry")),
					Text(" element with no id, which will never update"),
				),
				html.Li(Text("duplicate ids, which make every target ambiguous")),
				html.Li(
					Text("an "),
					html.Code(Text("fx-target")),
					Text(" or "),
					html.Code(Text("fx-loading-target")),
					Text(" selector that matches nothing"),
				),
				html.Li(
					Text("a "),
					html.Code(Text("meta[name=\"fx-refresh\"]")),
					Text(" with a missing or invalid interval or target"),
				),
				html.Li(Text("a "), html.Code(Text("form[fx-target]")), Text(" with no action")),
			),
			html.P(
				Text("Logging is off until you ask for it — "),
				html.Code(Text("fx.toggleLog(true)")),
				Text(", or"),
				Text(" "),
				html.Code(Text("?fx-log=true")),
				Text(" on any URL. The setting sticks for the tab's origin."),
			),
		),
		Section(
			"swaps",
			"What a swap actually does",
			html.P(Text("Worth knowing, because it explains most surprises:")),
			html.Ul(
				html.Li(
					Text(
						"The response is parsed into a detached document. Nothing in it runs, loads or renders until it is put in the page.",
					),
				),
				html.Li(
					Text("For each target, the matching element in the page is "),
					html.Em(Text("replaced")),
					Text(
						" — not its contents, the element. Anything the browser was holding on to inside it is gone: focus, selection, an open ",
					),
					html.Code(Text("<details>")),
					Text(", a playing video."),
				),
				html.Li(
					Text(
						"Scroll positions inside the fragment are saved and restored by position, so a scrolled table survives a poll.",
					),
				),
				html.Li(
					Text(
						"Scripts inside a swapped fragment are re-created so they run, in order, waiting for external ones to load before running the next.",
					),
				),
				html.Li(
					Text(
						"A target that is missing from the response is skipped, and a warning appears if",
					),
					Text(" "),
					html.Code(Text("fx.dev.js")),
					Text(" is loaded."),
				),
			),
		),
		Section(
			"not",
			"What fx does not do",
			html.P(
				Text(
					"No components, no client-side routing, no reactivity, no state management, no templates, no transitions, no request caching, no preloading, no partial-tree diffing, no WebSockets. None of these are on a roadmap, because the library's only real feature is that it is small.",
				),
			),
		),
	}
}
