// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package web

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func WhyPage() Page {
	return Page{
		Slug:  "why",
		Nav:   "Why",
		Title: "Why fx exists",
		Lede:  "A short argument for doing much less, and an honest account of what that costs.",
		Body:  whyBody,
	}
}

func whyBody(c *Ctx) Node {
	return Group{
		html.P(
			Text(
				"This started as a question I could not shake: why is building an internal tool in 2026 harder than it was with Rails in 2008?",
			),
		),
		html.P(
			Text(
				"Not slower — harder. The application I wanted was a few tables, some filters, a couple of forms and a detail pane. Every byte of truth in it lived in a database my server could reach. And the default way to build it involved a package manager, a bundler, a component framework, a client-side router, a data-fetching layer, a state library, and a second copy of my domain model written in TypeScript to keep the first one company.",
			),
		),
		html.P(
			Text(
				"None of that is bad engineering. All of it exists because someone had a real problem. The question is whether ",
			),
			html.Em(Text("I")),
			Text(
				" have that problem — and for a server-rendered internal tool, mostly, I do not.",
			),
		),
		Section(
			"cost",
			"The bill you are actually paying",
			html.P(
				Text(
					"A frontend toolchain is not a one-time cost. It is a subscription, and the charges show up in places that do not look like frontend work:",
				),
			),
			html.Ul(
				html.Li(
					html.Strong(Text("Two models of the same thing.")),
					Text(
						" The server knows what a record is. Now the client knows too, slightly differently, and the bugs live in the gap.",
					),
				),
				html.Li(
					html.Strong(Text("A build you have to keep alive.")),
					Text(
						" Toolchains rot. The version you pinned stops working with the Node you have, and an afternoon disappears.",
					),
				),
				html.Li(
					html.Strong(Text("A dependency graph nobody has read.")),
					Text(
						" A modest app pulls in hundreds of packages, each of which can run arbitrary code on your machine at install time.",
					),
				),
				html.Li(
					html.Strong(Text("A hiring and onboarding tax.")),
					Text(
						" My team writes Go. Asking everyone to also become competent in a frontend stack is expensive once, and expensive again every year the stack moves.",
					),
				),
			),
			html.P(
				Text(
					"For a product where the client genuinely is the application — a design tool, an editor, a game — that bill buys something worth having. For a page that shows rows from a database and lets you filter them, it buys a slightly nicer transition.",
				),
			),
		),
		Section(
			"wanted",
			"What I actually wanted",
			html.P(
				Text(
					"A website. A real one, where clicking a link asks the server for a page and the server sends one back. Then, on top of that and changing none of it, the ability to say",
				),
				html.Em(
					Text(
						"“only this part of the page is different, so only replace that part.”",
					),
				),
			),
			Pull(
				Text(
					"Not a client application that happens to talk to a server. A website that happens to skip the reload.",
				),
			),
			html.P(
				Text(
					"That ordering matters more than anything else on this page. If the enhanced path is the real path and the plain path is a degraded fallback, you have not built a website — you have built a client app with a courtesy exit. Sooner or later the plain path stops working and nobody notices, because nobody uses it.",
				),
			),
		),
		Section(
			"htmx",
			"Why not HTMX",
			html.P(
				Text(
					"HTMX is good software and it got a lot of people to reconsider the server. It did not fit, and the reason is a mental model rather than a missing feature.",
				),
			),
			html.P(
				Text(
					"In HTMX, the unit is the element. An element issues a request, and the response is",
				),
				html.Em(Text("that element's")),
				Text(
					" new contents. Follow that to its conclusion and your server grows a route per fragment — ",
				),
				html.Code(Text("/rows")),
				Text(", "),
				html.Code(Text("/row/7/status")),
				Text(","),
				html.Code(Text("/sidebar")),
				Text(
					" — each returning a piece of HTML that only makes sense in the context of a page it never renders.",
				),
			),
			Cols(
				Snippet(
					"html",
					"element-centric",
					`
<button hx-get="/rows?page=2"
        hx-target="#rows"
        hx-swap="outerHTML">
  Next
</button>

<!-- the server needs a /rows route that
     renders rows and nothing else -->
`,
				),
				Snippet(
					"html",
					"page-centric",
					`
<a href="/reports?page=2"
   fx-target="#rows">
  Next
</a>

<!-- the server renders /reports, the
     same as it does for a reload -->
`,
				),
			),
			html.P(
				Text(
					"The practical consequence: with the element-centric model there is often no URL that renders the state you are looking at. You can reach page 2 by clicking, but you cannot link to it, refresh into it, or send it to a colleague — unless you do extra work to keep the address bar in sync with a state the server never renders on its own.",
				),
			),
			html.P(
				Text("And the surface grows to match. "),
				html.Code(Text("hx-swap")),
				Text(" with a dozen strategies,"),
				html.Code(Text("hx-swap-oob")),
				Text(", "),
				html.Code(Text("hx-trigger")),
				Text(" with its own event mini-language,"),
				html.Code(Text("hx-boost")),
				Text(
					" to make ordinary links behave like the rest, plus an extension system. Each piece is reasonable. Together they are a framework, and I went looking because I did not want one.",
				),
			),
		),
		Section(
			"unpoly",
			"Why not Unpoly",
			html.P(
				Text(
					"Unpoly was much closer, and I want to be clear about that: it is page-centric, it treats real navigation as the foundation, and two of the best ideas in fx are lifted directly from it. Unpoly's ",
				),
				html.Code(Text("[up-hungry]")),
				Text(" is "),
				html.Code(Text("fx-hungry")),
				Text(". Unpoly's"),
				html.Code(Text("X-Up-Target")),
				Text(" request header is "),
				html.Code(Text("FX-Target")),
				Text(
					". Neither is my invention and I would rather say so on the front page than in a footnote.",
				),
			),
			html.P(
				Text(
					"What I could not get comfortable with was how much it does for you. Layers and overlays, caching and preloading, form validation, transitions, compilers, a navigation model with opinions about history I kept having to work around. When Unpoly did what I meant, it was lovely. When it did not, I was reading library source to find out why my back button had behaved that way — and that is exactly the afternoon I was trying to stop spending.",
				),
			),
			Pull(
				Text(
					"A large API surface costs the same whether the code is mine or not. Eventually, managing the library is the framework work I left to avoid.",
				),
			),
			html.P(
				Text(
					"So this is a fit judgement, not a verdict. If Unpoly's defaults match how you think, use Unpoly — it is more capable than fx and always will be. I wanted something I could hold entirely in my head, and “capable” is the opposite of that.",
				),
			),
		),
		Section(
			"rules",
			"The rules fx is built on",
			html.H3(Text("1. Simplicity beats performance")),
			html.P(
				Text(
					"fx re-fetches the whole page and throws most of it away. That is wasteful and it is the single most important decision in the library, because it is what keeps the code at a size a person can read in one sitting. When you need the waste back, read the",
				),
				html.Code(Text("FX-Target")),
				Text(
					" header and render less. That choice is yours, per handler, and you make it when you have a reason.",
				),
			),
			html.H3(Text("2. The server owns the page")),
			html.P(
				Text(
					"There is one renderer, and it is the one you already have. fx never composes, never templates, never decides what a page should contain. It reads a document your server wrote and moves elements out of it.",
				),
			),
			html.H3(Text("3. The URL is the state")),
			html.P(
				Text(
					"Filters, sort order, which row is open, which modal is showing — all of it goes in the query string. Then a refresh reproduces the screen exactly, the back button does the obvious thing, and a colleague who pastes your link sees what you see. On an internal tool that last one is not a nicety; it is most of the job.",
				),
			),
			html.H3(Text("4. Fail into the browser")),
			html.P(
				Text(
					"A timeout, a 500, a fragment missing from the response: every failure ends with the browser doing the navigation itself. Worst case, the user gets a page load — which is what they would have got anyway if you had never added the library.",
				),
			),
			html.H3(Text("5. Small enough to read is small enough to change")),
			html.P(
				Text(
					"fx is one file you can open, understand and edit. It has no build step, no package, no lockfile and no dependency. If it does not do what you need, the fix is in front of you instead of in an issue tracker.",
				),
			),
		),
		Section(
			"supply-chain",
			"The part about npm",
			html.P(
				Text(
					"There is a second reason to want a file instead of a package, and it stopped being theoretical some time ago. Installing a JavaScript dependency runs install scripts from the whole transitive graph with your user's privileges — your SSH keys, your cloud credentials, your browser profile. Every few months another popular package is compromised and everybody's CI runs the payload.",
				),
			),
			html.P(
				Text(
					"fx is a file. You can read all of it in the time it takes to read this page, copy it into your repository, and never think about its supply chain again, because it does not have one.",
				),
			),
		),
		Section(
			"costs",
			"What this costs you",
			html.P(Text("An honest list, because a pitch without one is marketing:")),
			html.Ul(
				html.Li(
					html.Strong(Text("More bytes over the wire.")),
					Text(
						" Every navigation fetches a whole document to use part of it. On a slow connection with a heavy page, that is a real cost — until you implement ",
					),
					html.Code(Text("FX-Target")),
					Text(", which is the entire point of that header existing."),
				),
				html.Li(
					html.Strong(Text("Server round-trips for things a client could do alone.")),
					Text(
						" Toggling a disclosure or sorting a loaded table goes back to the server. Sometimes that is silly. Write six lines of JavaScript for those, and keep fx for navigation.",
					),
				),
				html.Li(
					html.Strong(Text("No component model.")),
					Text(
						" Reuse is whatever your server-side templating gives you. If your templating is bad, fx will not save you.",
					),
				),
				html.Li(
					html.Strong(Text("Element identity is not preserved.")),
					Text(" A swap replaces elements outright, so a focused input or an open "),
					html.Code(Text("<details>")),
					Text(
						" inside a swapped fragment is gone. fx restores scroll positions and nothing else. Target more narrowly, or keep the stateful part outside the fragment.",
					),
				),
				html.Li(
					html.Strong(Text("It will not carry a rich client.")),
					Text(
						" If your application's state genuinely lives in the browser, fx is the wrong tool and no amount of attributes will change that.",
					),
				),
			),
			Note(
				"Where the line actually falls",
				html.P(
					Text(
						"Every app has a corner with real local state — a spreadsheet grid, a chart, a canvas. Use a proper library there. fx has nothing to say about it, holds no global state, and will not fight you. The mistake is letting that one corner decide the architecture of the other twenty screens.",
					),
				),
			),
		),
		Section(
			"next",
			"Next",
			html.P(
				html.A(
					html.Href("/patterns"),
					Attr("fx-target", "#content"),
					Attr("fx-loading-target", "#progress-bar"),
					Text("Fragment-driven development"),
				),
				Text(" "),
				Text("is how you actually build screens this way, and"),
				Text(" "),
				html.A(
					html.Href("/demo"),
					Attr("fx-target", "#content"),
					Attr("fx-loading-target", "#progress-bar"),
					Text("the demo"),
				),
				Text(" "),
				Text(
					"is an application doing it, with a log of every request so you can watch the protocol work.",
				),
			),
		),
	}
}
