// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package web

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func IndexPage() Page {
	return Page{
		Slug:  "",
		Nav:   "Overview",
		Title: "fx — Fragment eXchange",
		Lede:  "Your server already knows how to render the page. fx swaps the parts that changed. One attribute, 400 lines, no build step.",
		Body:  indexBody,
	}
}

func indexBody(c *Ctx) Node {
	return Group{
		html.Div(
			html.Class("hero-cta"),
			html.A(
				html.Class("btn btn-primary"),
				html.Href("/demo"),
				Attr("fx-target", "#content"),
				Attr("fx-loading-target", "#progress-bar"),
				Text("See it running"),
			),
			html.A(
				html.Class("btn"),
				html.Href("/why"),
				Attr("fx-target", "#content"),
				Attr("fx-loading-target", "#progress-bar"),
				Text("Why it exists"),
			),
			html.A(
				html.Class("btn"),
				html.Href("/reference"),
				Attr("fx-target", "#content"),
				Attr("fx-loading-target", "#progress-bar"),
				Text("Reference"),
			),
		),
		Snippet(
			"html",
			"the entire library, used",
			`
<script src="/fx.js"></script>

<a href="/reports" fx-target="#content">Reports</a>

<main id="content">
  <!-- whatever your server rendered -->
</main>
`,
		),
		html.P(
			Text("Click the link and fx fetches "),
			html.Code(Text("/reports")),
			Text(", pulls "),
			html.Code(Text("#content")),
			Text(
				" out of the response, puts it in the page and updates the address bar. No full reload, no flash, no scroll jump.",
			),
		),
		html.P(
			Text(
				"Turn JavaScript off and the same link still works, because it is a link to a page your server renders. That is not a fallback bolted on afterwards. It is the starting point.",
			),
		),
		Pull(
			Text(
				"A site built with fx is a site that works without fx. The library only makes it quicker.",
			),
		),
		Section(
			"what",
			"What it does",
			html.P(Text("Four things. That is the whole library.")),
			Table(
				[]string{"", "What it is for"},
				[][]Node{
					Row(
						C("fx-target"),
						Text("On a link or a form: fetch the page, swap these selectors."),
					),
					Row(
						C("fx-loading-target"),
						Text("Put an fx-loading class on these while the request is in flight."),
					),
					Row(
						C("fx-hungry"),
						Text("On any element with an id: swap me too, on every navigation."),
					),
					Row(
						C(`<meta name="fx-refresh">`),
						Text("Re-fetch this page on an interval and swap a fragment."),
					),
				},
			),
			html.P(
				Text(
					"There is a fifth thing, and it lives on your side: every request carries an",
				),
				html.Code(Text("FX-Target")),
				Text(
					" header naming the fragments the browser is about to use. Your handler can read it and skip the work nobody asked for. It is entirely optional — a handler that ignores it is correct, just slower.",
				),
			),
		),
		Section(
			"how",
			"How a navigation works",
			Steps(
				Text("You click a link that has fx-target."),
				Text("fx pushes the URL and fetches it, with an FX-Target header."),
				Text(
					"The server renders a page. A whole page — the same one it would render for a reload.",
				),
				Text(
					"fx parses the response in memory and lifts out the fragments named by fx-target.",
				),
				Text(
					"Those elements replace the ones in the page, and inline scripts inside them run.",
				),
				Text(
					"Anything goes wrong — a timeout, a 500, a missing fragment — and the browser does the navigation itself.",
				),
			),
			html.P(
				Text(
					"No virtual DOM, no hydration, no client-side router, no store. The page state lives in the URL, which means the back button, a refresh, and a link pasted into chat all show the same thing.",
				),
			),
		),
		Section(
			"install",
			"Install",
			html.P(Text("Copy the file. That is the install.")),
			Code("bash", `curl -O https://fx.ciuffolo.com/fx.js`),
			html.P(
				Text(
					"There is no package, no lockfile and no transitive dependency to audit, because there is nothing to depend on. If you write Go, the repository also ships a small package that embeds the script and answers the header:",
				),
			),
			Snippet(
				"go",
				"main.go",
				`
mux.Handle("GET /fx.js", fx.Handler())

func reports(w http.ResponseWriter, r *http.Request) {
	var rows []Row
	if fx.Wants(r, "#results") {
		rows = expensiveQuery(r) // skipped when only the nav is being swapped
	}
	render(w, rows)
}
`,
			),
		),
		Section(
			"suits",
			"What it is good at, and what it is not",
			html.P(
				Text(
					"fx is for applications whose truth lives on the server: internal tools, dashboards, admin panels, anything table-shaped and data-heavy. If your team writes backend code and your pages are already server-rendered, fx makes them feel like an application without making you build one.",
				),
			),
			html.P(
				Text(
					"It is not a framework and does not want to become one. There are no components, no reactivity, no client-side state and no template system, on purpose. When a corner of your page genuinely needs local state — a spreadsheet grid, a chart with a brush, a drag-and-drop canvas — use a real library for that corner. fx has no opinion about it and will not get in the way.",
				),
			),
			Note(
				"The design rule",
				html.P(
					Text(
						"When simplicity and performance disagree, simplicity wins. fx re-fetches whole pages and throws most of the response away. That is wasteful, and it is exactly why the library fits in your head in one sitting. If you want the waste back, the",
					),
					html.Code(Text("FX-Target")),
					Text(" header is right there."),
				),
			),
		),
	}
}
