// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package web

import (
	"fmt"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
	"strconv"
	"strings"
)

func DemoPage() Page {
	return Page{
		Slug:  "demo",
		Nav:   "Demo",
		Title: "A small application",
		Lede:  "A job runner, built the way this site argues for. Everything you can see is in the URL. Watch the request log while you click.",
		Wide:  true,
		Body:  demoBody,
	}
}

func demoBody(c *Ctx) Node {
	f := filtersFrom(c.R)
	all := jobs(c.start, requeuedFrom(c.R))

	// Order matters: each fragment records what it did as it is built, and the
	// log panel at the end renders that record. The page describes itself.
	summary := SummaryPanel(c, all)
	table := JobsPanel(c, f, all)
	detail := DetailPanel(c, f, all)

	return Group{
		html.Meta(
			html.Name("fx-refresh"),
			html.ID("jobs-poll"),
			Attr("fx-interval", "3000"),
			Attr("fx-target", "#jobs, #detail"),
		),
		summary,
		html.Div(
			html.Class("demo-grid"),
			html.Div(FiltersForm(f), table),
			html.Div(detail, LogPanel(c)),
		),
		DemoNotes(),
	}
}

// FiltersForm is a GET form, so submitting it changes the URL. That is the
// whole state management story.
func FiltersForm(f Filters) Node {
	var options []Node
	for _, s := range []string{"all", "running", "queued", "passed", "failed"} {
		opt := html.Option(html.Value(s), Text(s))
		if f.Status == s || (f.Status == "" && s == "all") {
			opt = html.Option(html.Value(s), html.Selected(), Text(s))
		}
		options = append(options, opt)
	}

	return html.Form(
		html.Class("filters"),
		html.Action("/demo"),
		html.Method("GET"),
		Attr("fx-target", "#jobs, #detail, #summary"),
		Attr("fx-loading-target", "#progress-bar"),
		html.Input(
			html.Type("search"),
			html.Name("q"),
			html.Value(f.Query),
			html.Placeholder("filter by job or pipeline"),
		),
		html.Select(html.Name("status"), Group(options)),
		If(
			f.Open != "",
			html.Input(html.Type("hidden"), html.Name("open"), html.Value(f.Open)),
		),
		html.Button(html.Type("submit"), html.Class("primary"), Text("Filter")),
		html.A(
			html.Class("btn"),
			html.Href("/demo"),
			Attr("fx-target", "#jobs, #detail, #summary"),
			Attr("fx-loading-target", "#progress-bar"),
			Text("Reset"),
		),
	)
}

// SummaryPanel is the expensive fragment. The poller never asks for it, so on
// a poll the handler never pays for it.
func SummaryPanel(c *Ctx, all []Job) Node {
	if !c.Wants("#summary") {
		c.entry.skip("#summary", summaryCost)
		return html.Div(html.ID("summary"), html.Class("panel"), Attr("hidden"))
	}

	c.entry.render("#summary")
	s := summarize(all)

	var cells []Node
	for _, status := range []string{"running", "queued", "passed", "failed"} {
		cells = append(cells, html.Div(
			html.Span(html.Class("pill pill-"+pillClass(status)), Text(status)),
			html.Div(
				html.Class("mono"),
				html.Style("font-size:22px;margin-top:6px"),
				Text(strconv.Itoa(s.Counts[status])),
			),
		))
	}

	return html.Div(
		html.ID("summary"),
		html.Class("panel"),
		html.Style("margin-bottom:20px"),
		html.Div(
			html.Class("panel-head"),
			Text("roll-up"),
			html.Span(
				html.Class("muted"),
				html.Style("text-transform:none;letter-spacing:0"),
				Text("— pretend this is a 250ms aggregate query"),
			),
		),
		html.Div(
			html.Class("panel-body"),
			html.Style("display:flex;gap:36px"),
			Group(cells),
		),
	)
}

func JobsPanel(c *Ctx, f Filters, all []Job) Node {
	if !c.Wants("#jobs") {
		c.entry.skip("#jobs", 0)
		return html.Div(html.ID("jobs"), html.Class("panel"), Attr("hidden"))
	}
	c.entry.render("#jobs")

	var rows []Node
	for _, j := range all {
		if !f.match(j) {
			continue
		}
		rows = append(rows, JobRow(f, j))
	}

	body := html.TBody(Group(rows))
	if len(rows) == 0 {
		body = html.TBody(
			html.Tr(
				html.Td(
					html.ColSpan("4"),
					html.Div(html.Class("empty"), Text("Nothing matches that filter.")),
				),
			),
		)
	}

	return html.Div(
		html.ID("jobs"),
		html.Class("panel"),
		html.Div(html.Class("panel-head"), Text("jobs")),
		html.Table(
			html.Class("jobs"),
			html.THead(
				html.Tr(
					html.Th(Text("job")),
					html.Th(Text("pipeline")),
					html.Th(Text("status")),
					html.Th(),
				),
			),
			body,
		),
	)
}

func JobRow(f Filters, j Job) Node {
	var progress Node
	if j.Status == "running" {
		progress = html.Div(
			html.Class("bar"),
			html.Span(html.Style(fmt.Sprintf("width:%d%%", j.Percent))),
		)
	}

	row := html.Tr(
		If(f.Open == j.ID, Attr("aria-selected", "true")),
		html.Td(html.Class("name"), Text(j.Name), progress),
		html.Td(html.Class("muted small"), Text(j.Pipeline)),
		html.Td(
			html.Span(html.Class("pill pill-"+pillClass(j.Status)), Text(j.Status)),
			If(
				j.Requeued,
				html.Span(html.Class("pill"), html.Style("margin-left:6px"), Text("requeued")),
			),
		),
		html.Td(
			html.A(
				html.Class("small"),
				html.Href(f.URL("open", j.ID)),
				Attr("fx-target", "#detail"),
				Attr("fx-loading-target", "#progress-bar"),
				Text("open"),
			),
		),
	)

	return row
}

// DetailPanel is a pane whose open/closed state is a query parameter, so the
// back button closes it and the URL can be pasted to somebody else.
func DetailPanel(c *Ctx, f Filters, all []Job) Node {
	if !c.Wants("#detail") {
		c.entry.skip("#detail", 0)
		return html.Aside(html.ID("detail"), html.Class("panel"), Attr("hidden"))
	}
	c.entry.render("#detail")

	if f.Open == "" {
		return html.Aside(
			html.ID("detail"),
			html.Class("panel"),
			html.Style("margin-bottom:20px"),
			html.Div(html.Class("panel-head"), Text("detail")),
			html.Div(
				html.Class("panel-body"),
				html.P(
					html.Class("empty"),
					html.Style("padding:14px 0"),
					Text("Open a job to see it here."),
				),
			),
		)
	}

	var job *Job
	for i := range all {
		if all[i].ID == f.Open {
			job = &all[i]
			break
		}
	}

	if job == nil {
		return html.Aside(
			html.ID("detail"),
			html.Class("panel"),
			html.Style("margin-bottom:20px"),
			html.Div(html.Class("panel-head"), Text("detail")),
			html.Div(
				html.Class("panel-body"),
				html.P(html.Class("empty"), Text("No job "), Text(f.Open), Text(".")),
			),
		)
	}

	return html.Aside(
		html.ID("detail"),
		html.Class("panel"),
		html.Style("margin-bottom:20px"),
		html.Div(
			html.Class("panel-head"),
			Text("job "),
			Text(job.ID),
			html.A(
				html.Style("margin-left:auto;text-transform:none"),
				html.Href(f.URL("open", "")),
				Attr("fx-target", "#detail"),
				Attr("fx-loading-target", "#progress-bar"),
				Text("close"),
			),
		),
		html.Div(
			html.Class("panel-body"),
			html.P(html.Class("mono"), html.Style("margin-bottom:8px"), Text(job.Name)),
			html.P(
				html.Class("small muted"),
				Text("pipeline "),
				Text(job.Pipeline),
				Text(" · "),
				Text(job.Took.String()),
				Text(" ·"),
				html.Span(html.Class("pill pill-"+pillClass(job.Status)), Text(job.Status)),
			),
			html.Form(
				html.Action("/demo/requeue"),
				html.Method("POST"),
				Attr("fx-target", "#jobs, #detail, #summary"),
				Attr("fx-loading-target", "#progress-bar"),
				html.Input(html.Type("hidden"), html.Name("id"), html.Value(job.ID)),
				html.Input(html.Type("hidden"), html.Name("q"), html.Value(f.Query)),
				html.Input(html.Type("hidden"), html.Name("status"), html.Value(f.Status)),
				html.Button(html.Type("submit"), html.Class("primary"), Text("Requeue")),
			),
		),
	)
}

// LogPanel is hungry: no link asks for it, and it updates on every swap.
func LogPanel(c *Ctx) Node {
	var items []Node
	for _, e := range c.log.snapshot() {
		items = append(items, LogRow(e))
	}

	if len(items) == 0 {
		items = append(items, html.Li(html.Class("muted"), Text("nothing yet")))
	}

	return html.Div(
		html.ID("server-log"),
		html.Class("panel"),
		Attr("fx-hungry"),
		html.Div(html.Class("panel-head"), Text("server log")),
		html.Div(html.Class("panel-body"), html.Ul(html.Class("log"), Group(items))),
	)
}

func LogRow(e *logEntry) Node {
	target := html.Span(html.Class("full"), Text("page load — rendered everything"))
	if e.Target != "" {
		target = html.Span(Text("FX-Target: "), html.Span(html.Class("t"), Text(e.Target)))
	}

	var note Node
	if e.Note != "" {
		note = html.Div(html.Class("t"), Text(e.Note))
	}

	var saved Node
	if len(e.Skipped) > 0 {
		saved = html.Div(
			html.Class("skip"),
			Text("skipped "),
			Text(strings.Join(e.Skipped, ", ")),
			If(e.Saved > 0, Text(fmt.Sprintf(" — saved ~%dms", e.Saved.Milliseconds()))),
		)
	}

	return html.Li(
		html.Div(
			html.Span(html.Class("m"), Text(e.Method)),
			Text(" "),
			Text(truncate(e.Path, 46)),
		),
		html.Div(target),
		note,
		saved,
		html.Div(html.Class("m"), Text(ago(e.At))),
	)
}

func DemoNotes() Node {
	return html.Div(
		html.Style("max-width:760px;margin-top:48px"),
		Section(
			"watching",
			"What to watch for",
			html.Ul(
				html.Li(
					html.Strong(Text("The poller.")),
					Text(" Every three seconds the page re-fetches itself asking for"),
					Text(" "),
					html.Code(Text("#jobs, #detail")),
					Text(
						". The log shows the roll-up being skipped each time — about 250ms of database work this page never does.",
					),
				),
				html.Li(
					html.Strong(Text("Open a job.")),
					Text(" That link asks only for "),
					html.Code(Text("#detail")),
					Text(", so the table and the roll-up are both skipped. The URL gains "),
					html.Code(Text("?open=…")),
					Text(
						", and the back button closes the pane because closing it is a URL you have already been to.",
					),
				),
				html.Li(
					html.Strong(Text("Filter.")),
					Text(
						" A plain GET form. The fields land in the query string, the address bar describes what you are looking at, and a refresh reproduces it exactly.",
					),
				),
				html.Li(
					html.Strong(Text("Requeue.")),
					Text(" A POST that answers "),
					html.Code(Text("303 See Other")),
					Text(
						". fx follows the redirect, swaps from the page it landed on and rewrites the URL — so a refresh re-reads instead of re-submitting.",
					),
				),
				html.Li(
					html.Strong(Text("Turn JavaScript off and use it anyway.")),
					Text(
						" Everything still works. It just reloads the page each time, which is what it was always doing underneath.",
					),
				),
			),
			Note(
				"The log is the point",
				html.P(
					Text("That panel is "),
					html.Code(Text("fx-hungry")),
					Text(
						": nothing links to it and no link asks for it, yet it updates on every swap. It is also the honest measure of this whole idea — the server is being asked for a page, every time, and it decides how much of one to build.",
					),
				),
			),
		),
	)
}

func pillClass(status string) string {
	switch status {
	case "running":
		return "running"
	case "passed":
		return "done"
	case "failed":
		return "failed"
	default:
		return "queued"
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}
